# Run: docker build -f docker/Dockerfile.cuda -t homr . && docker run --gpus all --rm -p 8080:8000 homr
# And then send images: curl -X POST -F "file=@tabi.jpg" http://localhost:8080/process --output tabi.musicxml

FROM python:3.11

WORKDIR /app

RUN apt update && apt install -y libgl1

RUN curl -sSL https://install.python-poetry.org | python3 -

RUN git clone https://github.com/liebharc/homr .

RUN /root/.local/bin/poetry install --only main --extras cuda

RUN /root/.local/bin/poetry run pip install --no-cache-dir -r docker/requirements.txt

# Pre-download models
RUN /root/.local/bin/poetry run python homr/main.py --init

EXPOSE 8000

CMD ["/root/.local/bin/poetry", "run", "uvicorn", "docker.api:app", "--host", "0.0.0.0", "--port", "8000"]
